#! /bin/sh

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        log_daemon_msg "Starting SDB Daemon..." "sdbd"
        if start-stop-daemon --start --quiet --background --make-pidfile --pidfile /var/run/sdbd.pid --exec /usr/sbin/sdbd; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
  stop)
        log_daemon_msg "Stopping SDB Daemon..." "sdbd"
        if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/sdbd.pid; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
  restart)
        log_daemon_msg "Restarting SDB Daemon..." "sdbd"
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/sdbd.pid
	sleep 1        
        if start-stop-daemon --start --quiet --background --make-pidfile --pidfile /var/run/sdbd.pid --exec /usr/sbin/sdbd; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
  *)
	log_action_msg "Usage: /etc/init.d/sdbd {start|stop|restart}"
	exit 1
esac

exit 0
